### ISSUE TITLE
Перевод на русский язык.

### ISSUE THREAD

**Issue by khorevaa** [pbazeliuk/IHL#108]
Планируется ли?

**Comment by pbazeliuk** [comment]
Языки интерфейса:
1. Английский 100%
2. Канадский (английский) 100%
3. Русский 100%
4. Украинский (в процессе локализации) 

Язык исходного кода:
Только английский, перевод не планируется

**Comment by khorevaa** [comment]
О. И это хорошо. Жаль что исходники не на русском, но ничего в частном порядке исправим :) синонимами экспортных функций

**Comment by pbazeliuk** [comment]
Обратите внимание, что лицензия строгая и ваши доработки нужно будет размещать в открытом доступе для ознакомления и скачивания сообществом.

До официального релиза, еще 4-5 месяцев, многое еще изменится в плане структуры данных. Так же есть ряд недоработок (формы сообщений, формы фоновых заданий, формы измерения производительности и нет документации, с инструментом могут работать только те кто в теме и понимает суть, но если есть время разобраться прошу :))  

P. S. Даже мои заметки в [Blog](https://pbazeliuk.com/) и на [YouTube](https://www.youtube.com/watch?v=C3cj-1h6Cys&list=PLhmDx9KCMiylA7GgtmXiv4K5YZvHpylvw
) устарели уже.

**Comment by asheichenko** [comment]
Обнаружил нелокализованные участки
![image](https://user-images.githubusercontent.com/8320910/52960155-326cee00-33a9-11e9-8209-401111c183bb.png)
![image](https://user-images.githubusercontent.com/8320910/52960221-5f210580-33a9-11e9-95cc-96137b362fa7.png)

**Comment by pbazeliuk** [comment]
Generate - исправлено.
Второе нужно подумать, наверное наименование необходимо задавать при активации подсистемы.
