### ISSUE TITLE
Добавить возможность дополнения имени файла датой создания

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#165]
Сейчас при создании формата файла csv есть возможность указать либо только имя файла, либо задать автогенерацию. Возможно будет полезной признак при установке которого в конец файла будет дописываться дата и время создания, чтобы не перезатирать предыдущий файл, если для него указано имя. Добавить можно на форму "Файловые параметры сообщения"
![image](https://user-images.githubusercontent.com/8320910/52466691-38d2bd00-2b94-11e9-87ea-329bd94194e1.png)

**Comment by pbazeliuk** [comment]
Спасибо, было бы полезно, принято.

**Comment by asheichenko** [comment]
Возможно я бы смог взяться за эту задачу. Вы pull request примите?

**Comment by pbazeliuk** [comment]
> Возможно я бы смог взяться за эту задачу. Вы pull request примите?

Задача уже выполнена, и планируется сегодня(12.02)-завтра(13.02) выложить.

**Comment by pbazeliuk** [comment]
Перенесено. Готово.

**Comment by asheichenko** [comment]
Коллеги из BI написали, что SQL не очень воспринимает такой формат даты времени.
![default](https://user-images.githubusercontent.com/8320910/52946936-53701780-3386-11e9-94ca-7ffc38e13453.png)

**Comment by asheichenko** [comment]
Вот так работает select convert(datetime, '2019-02-18T14:05:04.337',126 ) . 
А почему был выбран именно этот формат времени?

**Comment by pbazeliuk** [comment]
> Вот так работает select convert(datetime, '2019-02-18T14:05:04.337',126 ) .
> А почему был выбран именно этот формат времени?

В файловой системе нельзя сохранять файлы которые содержат `:`
Это формат ISO, если есть предложения могу выслушать

**Comment by asheichenko** [comment]
Ну возможно, добавить форматную строку, чтобы можно было выбирать формат даты. 
Коллеги из BI хотели бы в формате ИмяФайла_ГГГГММДДччммсс.csv
