### ISSUE TITLE
Добавить возможность архивирования при выгрузке в файлы

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#167]
Было бы неплохо иметь возможность настройки при выгрузке в файлы сразу же архивировать выгружаемый файл.

**Comment by pbazeliuk** [comment]
ZipFileWriter подойдет?

`New ZipFileWriter(<FileName>, <Password>, <Commentaries>, <CompressionMethod>, <CompressionRatio>, <EncryptionMethod>, <Encoding>) `

**Comment by asheichenko** [comment]
Я думаю да

**Comment by pbazeliuk** [comment]
Готово.
