### ISSUE TITLE
Создание файла поставки при сборке подсистемы из исходников

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#169]
Подсистема встраивается в конфигурацию через файл поставки. Сейчас после сборки, файл поставки формируется вручную. Было бы удобно если бы при сборке файл поставки создавался автоматически через пакетный запуск /CreateDistributionFiles .

**Comment by pbazeliuk** [comment]
папка .\tasks есть, сборка планируется через `oscript` в будущем

**Comment by pbazeliuk** [comment]
Закрываю дубль #109
