### ISSUE TITLE
Объекты не входящие ни в одну подсистему

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#181]
Обнаружил объекты, которые не относятся ни к одной подсистеме.
![image](https://user-images.githubusercontent.com/8320910/53496860-fa099600-3ab3-11e9-9757-a73cf0c12510.png)

**Comment by pbazeliuk** [comment]
Да, косяк, спасибо.

**Comment by pbazeliuk** [comment]
Добавил.
