### ISSUE TITLE
SelfFiles добавление в путь "\" при необходимости

### ISSUE THREAD

**Issue by pbazeliuk** [pbazeliuk/IHL#186]
`{Обработка.FL_SelfFiles.МодульОбъекта(103)}: Ошибка при вызове метода контекста (Записать): Ошибка доступа к файлу '\\nas-01.ktc.local\Shara\PowerBiFactBonusManagerKPP.csv'. 5(0x00000005): Отказано в доступе.`

**Comment by asheichenko** [comment]
Тоже столкнулся с такой ошибкой. 
Еще одна особенность этой ошибки. Попытался воспроизвести исключение, если не указать "\" в пути, то исключение не генерируется. Например есть путь "\\erp\1C_files\test\" и имя файла "File.csv". 
![image](https://user-images.githubusercontent.com/8320910/54759614-80228380-4bff-11e9-8458-498d1096f68d.png)

Если я задам "\\erp\1C_files\tes" , то ошибку не выдаст и сгенерируется файл "\\erp\1C_files\tesFile.csv" .
Если я задам "\\erp\1C_files\tes\" , то также ошибку не выдаст и сгенерируется файл "\\erp\1C_files\tes\File.csv" , т.е. создастся каталог. Может добавить настройку типа "Создавать каталог", которая бы в зависимости от установки или ругалась или создавала каталог автоматически?

**Comment by pbazeliuk** [comment]
Наверное, лучше добавить справку что будут созданы каталоги если их нет.
