### ISSUE TITLE
Изменить метод НормализироватьИмяКолонки

### ISSUE THREAD

**Issue by vandalsvq** [pbazeliuk/IHL#2]
Поскольку метод предусматривает не все возможные варианты использованных символов, предлагаю альтернативную реализацию. Единственное я удалил преобразование символов после пробелов в верхний регистр. Если надо восстановите самостоятельно, мне лично это оказалось ни к чему. Я все равно вместе с данными передаю информацию о колонках, типах и других свойствах.

Для проверки использовал имя поля данных "[~' йо'{' ё'}"жик"|\/?><.,]". Можно туда добавить числа и латиницу, но в принципе это уже не существенно.

`// Возвращает нормализированное имя колонки, например, "Товары.Сумма"
// к виду: "ТоварыСумма". СКД допускает большой набор символов в именах, 
// но преобразовывает не цифры и буквы к _, а пробелы удаляет.
//
// Параметры:
// 	ПутьКДанным - Строка - колонка имя которой необходимо нормализировать.
//
// Возвращаемое значение:
// 	Строка - нормализированное имя колонки.
//
Функция ПолучитьИмяКолонки(ПутьКДанным) Экспорт
	Диапазоны = Новый Массив;
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 48, 57));		// цифры
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 65, 90));		// латиница большие
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 97, 122));		// латиница маленькие
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 1040, 1103));	// кириллица
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 1025, 1025));	// символ "Ё"
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 1105, 1105));	// символ "ё"
	Диапазоны.Добавить(Новый Структура("Мин,Макс", 95, 95));		// символ "_"	
	
	УдаляемыеСимволы = Новый Массив;
	УдаляемыеСимволы.Добавить(КодСимвола(Символы.НПП));
	УдаляемыеСимволы.Добавить(КодСимвола(" "));
	УдаляемыеСимволы.Добавить(КодСимвола("."));
	
	ДопустимыеСимволы = Новый Массив;
	Для Каждого СтруктураДиапазон Из Диапазоны Цикл
		Для КодСимвола = СтруктураДиапазон.Мин По СтруктураДиапазон.Макс Цикл
			ДопустимыеСимволы.Добавить(КодСимвола);
		КонецЦикла; 
	КонецЦикла;
	
	ИмяКолонки = "";
	Для Индекс = 1 По СтрДлина(ПутьКДанным) Цикл
		ЗначениеСимвола = Сред(ПутьКДанным, Индекс, 1);
		КодСимвола		= КодСимвола(ЗначениеСимвола);
		Если УдаляемыеСимволы.Найти(КодСимвола) <> Неопределено Тогда
			ЗначениеСимвола = "";
		ИначеЕсли ДопустимыеСимволы.Найти(КодСимвола) = Неопределено Тогда
			ЗначениеСимвола = "_";
		КонецЕсли;
		
		ИмяКолонки = ИмяКолонки + ЗначениеСимвола;
	КонецЦикла;
	
	Возврат ИмяКолонки;
КонецФункции`

**Comment by pbazeliuk** [comment]
Спасибо, за issue.
После проверки и реализации тестов, обязательно внесу изменения.

**Comment by pbazeliuk** [comment]
Использовать функцию Upper() необходимо, что бы преобразовать название в camel case. "Колонка один" -> "КолонкаОдин". Такую операцию так же делает и система компоновки данных.

Дополнительную проверку, необходимо делать в объекте ObjectStream. Различные форматы имеют различные ограничения при наименовании объектов. ColumnsCache дополнительно передается в объект потока перед началом вывода. Версия 0.5 будет для скачивания 12.02.2017.

**Comment by pbazeliuk** [comment]
Задача не является актуальной, основные причины согласно обработки по стеку вызовов:
- Добавлена поддержка псевдонимов\синонимов колонок, но пока они конвертируются в [PascalCase](https://en.wikipedia.org/wiki/PascalCase), в будущем эта конвертация возможно будет и вовсе отключена
- При встрече с запрещенными символами в названиях\псевдонимах\синонимах колонок, вывод будет автоматически переключен из режима `fast `в режим `sequential`
- Кэш колонок и группировок перед началом вывода передается в `StreamObject ` для проверки на соответствие формату и/или приведения к необходимому виду (зависит от реализации в `StreamObject`)
```1C-Enterprise
Procedure Output(Mediator, StreamObject, OutputParameters, 
    Val SaveResources = True) Export
    
    ...

    // Handle naming restrictions.
    // Object can have naming restrictions and this problems should be handled in place.
    StreamObject.VerifyGroupNames(Mediator, GroupNames);
    StreamObject.VerifyColumnNames(Mediator, TemplateColumns);

    ...

EndProcedure // Output()
```

По своей сути тем что будет выводиться полностью управляет `StreamObject `определенного формата.
