### ISSUE TITLE
Не копируются настройки обмена

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#206]
Сейчас не хватает функциональности копирования настроек обмена.
Если попробовать копировать  правой кнопкой мыши , добавить свое имя и записать. При этом не копируются настройки СКД. Сейчас надо отдельно сохранять настройку СКД и загружать в новый элемент.

**Comment by pbazeliuk** [comment]
Да есть, такое

**Comment by pbazeliuk** [comment]
Исправлено.
