### ISSUE TITLE
Роли для объектов подсистем

### ISSUE THREAD

**Issue by JohnyDeath** [pbazeliuk/IHL#211]
Сейчас в конфигурации нет ни одной роли.
Как предполагается встраивать подсистему в сторонние конфигурации? Создавать роли на объекты FL_ уже после слияния?
Быть может стоит добавить несколько ролей в сам FoxyLink. Как минимум нужны роли:
* на запись в справочники и регистры FL. Эту роль потом следует включать в базовый профиль основной конфигурации. (на текущий момент пользователь не с полными правами просто ничего не сможет сделать в базе)
* чтение всего
* изменение и интерактивный просмотр (админ FL)

**Comment by pbazeliuk** [comment]
Тестирую, две роли:

- FL_BasicRightsFoxyLink (Пользовательские права)
- FL_FullRightsFoxyLink (Административные права)
