### ISSUE TITLE
Ошибка в процедуре EventHandlerInfo общего модуля SocialNetworks_Events

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#216]
Версия обработчика инициализируется позже, чем формируется описание обработчика
![image](https://user-images.githubusercontent.com/8320910/67856219-14a17c80-fb25-11e9-8142-44b9da37715f.png)

**Comment by pbazeliuk** [comment]
Исправлено в версии выше 1.0.0.2

**Comment by pbazeliuk** [comment]
Перенесено в версии 0.9.9.75
