### ISSUE TITLE
Ухудшение производительности при отсутствии настроек обмена, для какого-либо издателя.

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#219]
Версия FoxyLink: 0.9.9.339
Версия платформы: 8.3.14.1694
Обнаружил следующую особенность, которая приводит к заметному падению производительности.
Имеем такую настройку для регистра сведений:
![image](https://user-images.githubusercontent.com/8320910/70447256-815a5000-1aaf-11ea-9081-e4fae4a33891.png)
Также есть настройка обмена данными:
![image](https://user-images.githubusercontent.com/8320910/70447375-a6e75980-1aaf-11ea-9537-1d71731c8357.png)
Настройка простая, используется запрос к регистру сведений "Замеры времени" для выгрузки в ELK.
В случае, когда в регистр пишется сразу несколько записей, через НаборЗаписей.Записать(), без установленного отбора, то в общем модуле FL_CommonUse в строке 261, запрос начинает работать без фильтров, что приводит к сканированию всей таблицы. Вот пример кода:
![image](https://user-images.githubusercontent.com/8320910/70447581-fcbc0180-1aaf-11ea-9d2f-38290209d872.png)
Вот как он выполняется на СУБД (пример из ТЖ, запрос начал выполнятся 2 секунды):
57:29.952000-2202969,DBMSSQL,5,t:applicationName=BackgroundJob,SessionID=19237,Usr=robot,Trans=1,dbpid=90,Sql='SELECT
T1._Fld64961RRef,
T1._Fld64962,
T1._Fld64963,
T1._Fld64964
FROM dbo._InfoRg64960 T1'

**Comment by asheichenko** [comment]
В итоге получаем, что в таблицу значений выгружается весь регистр
![image](https://user-images.githubusercontent.com/8320910/70506300-00489a80-1b3b-11ea-8026-99d0e0cb823f.png)

**Comment by pbazeliuk** [comment]
Очень интересно, проверю. Спасибо за информацию.

**Comment by pbazeliuk** [comment]
Базовая таблица обработки подписок в подсистеме:

* **CREATE (INSERT)**

| Parameter | `RegisterBeforeWrite` | `RegisterOnWrite` |
| ------------- | ------------- | ------------- |
| DataBase | ❌ | ✅ |
| Source | ✅ | ✅ |
| Replacing | `true` | `true` |

* **UPDATE (UPDATE)**

| Parameter | `RegisterBeforeWrite` | `RegisterOnWrite` |
| ------------- | ------------- | ------------- |
| DataBase | ✅ | ✅ |
| Source | ✅ | ✅ |
| Replacing | `true` | `true` |

* **DELETE (DELETE)**

| Parameter | `RegisterBeforeWrite` | `RegisterOnWrite` |
| ------------- | ------------- | ------------- |
| DataBase | ✅ | ❌ |
| Source | ❌ | ❌ |
| Replacing | `true` | `true` |

* **MERGE (MERGE)**

| Parameter | `RegisterBeforeWrite` | `RegisterOnWrite` |
| ------------- | ------------- | ------------- |
| DataBase | ✅ | ❌ |
| Source | ❌ | ❌ |
| Replacing | `true` | `true` |
| DataBase | ❌ | ✅ |
| Source | ✅ | ✅ |
| Replacing | `false` | `false` |

**Comment by pbazeliuk** [comment]
### Этот код должен решить проблему

```1c-enterprise
Procedure RegisterBeforeWrite(Source, Cancel, Replacing) Export
   
    Var DBSource, DBTablePrimaryKeys;
    
    If Source.DataExchange.Load OR Cancel Then
        Return;
    EndIf;
    
    SourceMetadata = Source.Metadata();
    EventSource = SourceMetadata.FullName();
    If NOT Catalogs.FL_Messages.IsPublisher(EventSource) Then
        Return;    
    EndIf;
    
    RecordsCount = Source.Count();
    DBRecordsCount = 0; 
    
    // If Replacing = True, it is needed to check database records if exists
    // to make decision about the type of operation.
    If Replacing Then
        
        DBTablePrimaryKeys = FL_CommonUse.PrimaryKeysByMetadataObject(
            SourceMetadata);
        DBSource = FL_CommonUse.RegisterAttributeValues(SourceMetadata, 
            Source.Filter, DBTablePrimaryKeys);
        DBRecordsCount = DBSource.Count();
        
    EndIf;
        
    // It is nothing to register, return.
    If RecordsCount = 0 AND DBRecordsCount = 0 Then
        Return;
    EndIf;
    
    Operation = RegisterMessageOperation(RecordsCount, DBRecordsCount, Replacing);
    If NOT Catalogs.FL_Messages.IsMessagePublisher(EventSource, Operation) Then
        Return;    
    EndIf;
    
    Invocation = Catalogs.FL_Messages.NewInvocation();
    Invocation.EventSource = EventSource;
    Invocation.Operation = Operation;
    
    // Saving invocation context.
    If Replacing Then
        FillRegisterContext(Invocation, DBTablePrimaryKeys, Source.Filter, 
            DBSource);   
    EndIf;

    Source.AdditionalProperties.Insert("Invocation", Invocation); 
         
EndProcedure // RegisterBeforeWrite()
```

**Comment by asheichenko** [comment]
Добавил код, проблема решена, после внесения этого изменения, можно задачу закрывать.

**Comment by pbazeliuk** [comment]
Закрою, когда будет код влит в репозиторий

**Comment by pbazeliuk** [comment]
Исправлено в релизе 1.0.6
