### ISSUE TITLE
Ускорение проверки, является ли объект метаданных издателем для подписки FL_RegistersBeforeWrite 

### ISSUE THREAD

**Issue by asheichenko** [pbazeliuk/IHL#228]
Подписка на событие FL_RegistersBeforeWrite может вызываться очень много раз при массовой записи объектов, при этом занимает до 30% времени выполнения. Большую часть занимает выполнение следующего кода:
![image](https://user-images.githubusercontent.com/8320910/87535557-5ddc3100-c6a0-11ea-88ce-3b516da2b5e2.png)
Возможны следующие варианта ускорения:
-  ограничить количество источников метаданных, используя только те что нам нужны. 
-  перенести функцию Catalogs.FL_Messages.IsPublisher(EventSource) в модуль с повторным использованием значений

**Comment by pbazeliuk** [comment]
#32 Прямо, противоположная задача

Можно попытаться сделать РегистрСведений со срезом последних

**Comment by pbazeliuk** [comment]
@asheichenko такое маленькое уточнение, а эти записи делаются в рамках одного серверного вызова?

**Comment by asheichenko** [comment]
Да, это один серверный вызов.

**Comment by asheichenko** [comment]
> #32 Прямо, противоположная задача
> 
> Можно попытаться сделать РегистрСведений со срезом последних

Не совсем понял идею с регистром сведений. А почему через повторное использование значений не хотите. По идее регистр FL_MessagePublishers не часто меняется и для него кэш может не должен быть оперативно актуальным.

**Comment by pbazeliuk** [comment]
@asheichenko в рамках одного серверного вызова, повторное использование значений имеет место на жизнь

**Comment by pbazeliuk** [comment]
Fixed. Будет исправлено, при заливке
