### ISSUE TITLE
События регистра сведений должны формировать несколько сообщений

### ISSUE THREAD

**Issue by pbazeliuk** [pbazeliuk/IHL#70]
При записи набора записей регистра сведений, должно быть создано:
- [x] Событие `Create` для записей которых не было при обработке события `ПередЗаписью`, и которые появились при обработке события`ПриЗаписи` набора. 
- [x] Событие `Update` для записей которые были при обработке события `ПередЗаписью`, и которые присутствуют при обработке события `ПриЗаписи` набора. 
- [x] Событие `Delete` для записей которые были при обработке события `ПередЗаписью`, и которые исчезли при обработке события `ПриЗаписи` . 
- [x] Важно анализировать только измерения

**Comment by nixel2007** [comment]
Интересно, как вы реализуете это с учетом "двойной" записи регистров сведений. правда интересно :) посмотрю реализацию.

**Comment by pbazeliuk** [comment]
@nixel2007 в принципе реализация уже есть, но определится какая верная довольно сложно.
Все что ниже описано, актуально для:
- Управляемые блокировки;
- клиент-серверная архитектура.

**Пока мысли в слух.**
Если обмен с DWH - логично выполнять операции `Create`, `Delete`, `Delete` -> `Create`
- для `Create` все просто, всегда параметр `Replacing = false`. Ориентируемся на `Source.Filter` и создаем `Job` с методом `Create`. (Не забываем посмотреть контекст, возможно это `Delete` -> `Create`);
- для `Delete` так же все просто, всегда параметр `Replacing = true` и перед записью есть записи в регистре по `Source.Filter` (создаем `Job` с методом `Delete`), если записей нет, то и фиксировать данное событие не нужно. (Не забываем записать контекст, возможно это `Delete` -> `Create`);
- для `Delete` -> `Create`, если записи есть, необходимо сохранить контекст (создаем `Job` с методом `Delete` и записываем контекст). При обработке `Create` создать событие с помощью `ContinueWith` и указать `Job` которое создали при обработке события `Delete`. 

Для других обменов, необходимо обрабатывать по другому `Delete` -> `Create`. Если `Source.Filter` контекстов равны\пересекаются, вычислить что добавили, изменили, удалили и создать три различных `Job`, но это так же накладывает ограничения на описание обмена. 

Пока вижу, что для события необходимо явно указывать как хочется его обрабатывать.
