### ISSUE TITLE
При поиске параметров в схеме приводить имена в верхний регистр

### ISSUE THREAD

**Issue by pumbaEO** [pbazeliuk/IHL#92]
При поиски параметров из таблицы InvocationContext необходимо делать поиск без учета регистра, соответсвенно, необходимо привести в верхний регистр. https://github.com/FoxyLinkIO/FoxyLink/blob/develop/src/CommonModules/FL_DataComposition/Ext/Module.bsl#L801 

Дополнительно в https://github.com/FoxyLinkIO/FoxyLink/blob/develop/src/CommonModules/FL_BackgroundJob/Ext/Module.bsl#L123 перобразовать в верхний регистр и отразить в документации, что при ручном заполнении InvocationContext необходимо PrimaryKey указывать вверхнем регистре.

**Comment by pbazeliuk** [comment]
Думаю, можно создать команду которая заполняет эти данные. `AddToInvocationContext`

**Comment by pbazeliuk** [comment]
Исправлено. Вечером залью в ветку.
